#!/bin/bash
# Download and convert 1000 Genomes high-coverage GRCh38 genotypes to PLINK2 format
# for all 22 autosomes + X. Processes one chromosome at a time to save disk space
# (downloads VCF → converts to pgen → deletes VCF before moving to next chromosome).
#
# Usage (login node, plink2 in PATH):
#   bash scripts/download_genotypes.sh
#
# Or submit as SLURM array job (one chromosome per task):
#   sbatch --array=1-22 scripts/download_genotypes.sh
#
# Requirements:
#   - plink2 in PATH  (export PATH=/projappl/project_2013539/cosinor-env/bin:$PATH)
#   - pipeline_output/raw/samples_EUR.txt  (generated by puhti_pipeline.py --step download)
#   - ~150 GB free disk space during processing (each VCF ~4-8 GB, deleted after conversion)

set -euo pipefail

# ── Environment ───────────────────────────────────────────────────────────────
# Add plink2 location to PATH (adjust if plink2 is elsewhere on your system)
export PATH="/projappl/project_2013539/cosinor-env/bin:/users/${USER}/.local/bin:${PATH}"

# ── Config ────────────────────────────────────────────────────────────────────
WORKDIR="/scratch/project_2013539/Erkka/tensorqtl"
GENO_DIR="${WORKDIR}/pipeline_output/geno"
SAMPLES="${WORKDIR}/pipeline_output/raw/samples_EUR.txt"
THREADS=8
MAF=0.01

VCF_BASE="https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased"

# ── Determine which chromosome(s) to process ─────────────────────────────────
# If running as SLURM array job, SLURM_ARRAY_TASK_ID is set (1–22)
# Otherwise process all chromosomes sequentially
if [ -n "${SLURM_ARRAY_TASK_ID:-}" ]; then
    CHROMS=("${SLURM_ARRAY_TASK_ID}")
else
    CHROMS=($(seq 1 22) X)
fi

mkdir -p "${GENO_DIR}"

for CHROM in "${CHROMS[@]}"; do
    PGEN="${GENO_DIR}/chr${CHROM}"

    # Skip if already converted
    if [ -f "${PGEN}.pgen" ]; then
        echo "[chr${CHROM}] Already exists, skipping."
        continue
    fi

    echo "[chr${CHROM}] Starting at $(date)"

    # ── Download VCF ──────────────────────────────────────────────────────────
    if [ "${CHROM}" = "X" ]; then
        VCF_FILE="CCDG_14151_B01_GRM_WGS_2020-08-05_chrX.filtered.eagle2-phased.v2.vcf.gz"
    else
        VCF_FILE="CCDG_14151_B01_GRM_WGS_2020-08-05_chr${CHROM}.filtered.shapeit2-duohmm-phased.vcf.gz"
    fi

    VCF_PATH="${GENO_DIR}/chr${CHROM}.vcf.gz"
    echo "[chr${CHROM}] Downloading ${VCF_FILE}..."
    wget -q --show-progress \
         "${VCF_BASE}/${VCF_FILE}" \
         -O "${VCF_PATH}"

    # ── Convert to pgen ───────────────────────────────────────────────────────
    echo "[chr${CHROM}] Converting to pgen..."
    plink2 \
        --vcf "${VCF_PATH}" \
        --keep "${SAMPLES}" \
        --maf ${MAF} \
        --make-pgen \
        --output-chr chrM \
        --out "${PGEN}" \
        --threads ${THREADS}

    # ── Delete VCF to free space ──────────────────────────────────────────────
    rm -f "${VCF_PATH}"
    echo "[chr${CHROM}] Done at $(date). Variants: $(wc -l < ${PGEN}.pvar)"
done

echo "All requested chromosomes processed."
echo "Pgen files in: ${GENO_DIR}"
ls -lh "${GENO_DIR}"/*.pgen 2>/dev/null | awk '{print $5, $9}'
